### ISSUE TITLE
Remove player with vimeo workaround on chrome

### ISSUE THREAD

**Issue by nuclearace** [calzoneman/sync#327]
Sound still plays after the player is removed.

**Comment by calzoneman** [comment]
Should be fixed.  See function `killVideoUntilItIsDead`

**Comment by nuclearace** [comment]
I think this issue is back. Might have something to do with the volume normalization, not sure. But switching to vimeo when you had sound on will cause the vimeo video to play with sound. (Video player is hidden)
